services:
  geminiclivscodeidecompanion:
    image: geminiclivscodeidecompanion
    build:
      context: packages/vscode-ide-companion
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
